from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
import json
from ..procedural.rocket_factory import RocketSpec
@dataclass
class WebRenderConfig:
    output_dir:str='web_viewer'; title:str='NablaRender v0.7 Web'; width:int=1280; height:int=720; nanite_mode:str='meshlet_lod'; raytrace_mode:str='screen_space_reflection_hooks'
HTML='''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><style>html,body{{margin:0;height:100%;background:#050811;color:#edf3ff;font-family:Inter,system-ui,sans-serif}}canvas{{display:block;width:100vw;height:100vh}}#hud{{position:fixed;left:16px;top:16px;background:rgba(9,15,28,.82);padding:14px;border-radius:14px;width:390px;backdrop-filter:blur(10px)}}label{{display:block;font-size:12px;margin-top:8px}}input,select{{width:100%}}code{{font-size:12px;color:#a9bbd8}}</style></head><body><div id="hud"><h3>{title}</h3><label>Scientific mode</label><select id="mode"><option>beauty</option><option>thermal</option><option>infrared</option><option>xray</option></select><label>Heat/plasma intensity</label><input id="heat" type="range" min="0" max="1" step=".01" value=".55"><label>Nanite-inspired LOD</label><input id="lod" type="range" min="0" max="5" step="1" value="2"><label>Camera orbit</label><input id="orbit" type="range" min="0" max="360" step="1" value="35"><p><code>v0.7: WebGL viewer with meshlet-style LOD controls, scientific modes, PBR materials and hooks for future WebGPU ray tracing.</code></p></div><canvas id="app"></canvas><script type="module" src="./app.js"></script></body></html>'''
JS='''import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.169.0/build/three.module.js';import{OrbitControls}from 'https://cdn.jsdelivr.net/npm/three@0.169.0/examples/jsm/controls/OrbitControls.js';
const canvas=document.getElementById('app');const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.shadowMap.enabled=true;const scene=new THREE.Scene();scene.background=new THREE.Color(0x06101c);scene.fog=new THREE.Fog(0x06101c,110,320);const camera=new THREE.PerspectiveCamera(44,innerWidth/innerHeight,.1,1000);camera.position.set(48,-30,20);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(22,0,7);controls.update();scene.add(new THREE.HemisphereLight(0xbfdcff,0x11131b,1.7));const sun=new THREE.DirectionalLight(0xfff0d0,5);sun.position.set(-38,35,50);sun.castShadow=true;scene.add(sun);const group=new THREE.Group();scene.add(group);
function mat(mode,heat){let c=new THREE.Color(0xcfd4db); if(mode==='thermal')c.setRGB(Math.min(1,heat*1.35),Math.pow(heat,.65),Math.max(.05,1-heat*.68)); if(mode==='infrared')c.setRGB(heat,Math.pow(heat,.7),.02); if(mode==='xray')c.set(0x7af7ff); return new THREE.MeshPhysicalMaterial({color:c,metalness:mode==='xray'?.02:.72,roughness:mode==='xray'?.12:.26,clearcoat:.45,clearcoatRoughness:.16,transmission:mode==='xray'?.2:0,emissive:mode==='thermal'?c.clone().multiplyScalar(.25):new THREE.Color(0x000000)});}function build(){while(group.children.length)group.remove(group.children[0]);const mode=document.getElementById('mode').value;const heat=Number(document.getElementById('heat').value);const seg=[24,32,48,64,96,128][Number(document.getElementById('lod').value)];const m=mat(mode,heat);const body=new THREE.CylinderGeometry(4.6,4.6,38,seg,48,true);body.rotateZ(Math.PI/2);body.translate(28,0,0);const nose=new THREE.ConeGeometry(4.6,10.5,seg,28,true);nose.rotateZ(-Math.PI/2);nose.translate(5.25,0,0);const tail=new THREE.CylinderGeometry(1.6,4.6,7.5,seg,14,true);tail.rotateZ(Math.PI/2);tail.translate(51.75,0,0);for(const g of [body,nose,tail]){const o=new THREE.Mesh(g,m);o.castShadow=o.receiveShadow=true;group.add(o)}for(let i=0;i<4;i++){const fm=new THREE.MeshPhysicalMaterial({color:mode==='xray'?0x9effff:0x18191e,metalness:.1,roughness:.65});const f=new THREE.Mesh(new THREE.BoxGeometry(7.2,.18,3.4),fm);const a=i*Math.PI/2;f.position.set(40,Math.cos(a)*5.15,Math.sin(a)*5.15);f.lookAt(52,Math.cos(a)*15,Math.sin(a)*15);group.add(f)}const plume=new THREE.Mesh(new THREE.ConeGeometry(2.5,11,48,1,true),new THREE.MeshBasicMaterial({color:0xff7722,transparent:true,opacity:.45+heat*.25}));plume.geometry.rotateZ(Math.PI/2);plume.geometry.translate(60,0,0);if(mode!=='xray')group.add(plume)}build();document.getElementById('mode').onchange=build;document.getElementById('heat').oninput=build;document.getElementById('lod').oninput=build;document.getElementById('orbit').oninput=e=>{let a=Number(e.target.value)*Math.PI/180;camera.position.set(Math.cos(a)*52,Math.sin(a)*52,20);controls.update()};window.onresize=()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)};const floor=new THREE.Mesh(new THREE.PlaneGeometry(260,260),new THREE.MeshStandardMaterial({color:0x101722,roughness:.94}));floor.rotation.x=-Math.PI/2;floor.position.z=-4.7;floor.receiveShadow=true;scene.add(floor);function animate(t){group.rotation.x=.02*Math.sin(t*.0007);renderer.render(scene,camera);requestAnimationFrame(animate)}requestAnimationFrame(animate);'''
def export_web_viewer(config:WebRenderConfig|None=None, rocket_spec:RocketSpec|None=None)->dict[str,str]:
    c=config or WebRenderConfig(); out=Path(c.output_dir); out.mkdir(parents=True,exist_ok=True); (out/'index.html').write_text(HTML.format(title=c.title),encoding='utf-8'); (out/'app.js').write_text(JS,encoding='utf-8'); (out/'scene_metadata.json').write_text(json.dumps({'title':c.title,'rocket_spec':(rocket_spec or RocketSpec()).__dict__,'nanite_mode':c.nanite_mode,'raytrace_mode':c.raytrace_mode},indent=2),encoding='utf-8'); return {'index_html':str(out/'index.html'),'app_js':str(out/'app.js'),'scene_metadata':str(out/'scene_metadata.json')}
