"""Build the deterministic ``math.txt`` mathematical-source amalgamation.

The bundle is a review/distribution artifact, not a second source of truth.  Edit
the referenced modules and regenerate this file instead of editing ``math.txt``.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "math.txt"
DIRECTORIES = (
    ROOT / "src/nablamath/math",
    ROOT / "src/nablamath/symbolic",
    ROOT / "src/nablamath/numeric",
    ROOT / "src/nablamath/autodiff",
    ROOT / "src/nablamath/physics",
    ROOT / "src/nablamath/gpu",
    ROOT / "lean",
)
FILES = (
    ROOT / "src/nablamath/expression.py",
    ROOT / "src/nablamath/orbits.py",
    ROOT / "src/nablamath/research.py",
    ROOT / "src/nablamath/schema/expression.py",
    ROOT / "src/nablamath/schema/units.py",
)
SUFFIXES = {".py", ".lean"}


def mathematical_sources() -> tuple[Path, ...]:
    """Return every canonical mathematical source in stable path order."""
    selected = {path for path in FILES if path.is_file()}
    for directory in DIRECTORIES:
        if directory.is_dir():
            selected.update(
                path
                for path in directory.rglob("*")
                if path.is_file()
                and path.suffix in SUFFIXES
                and "__pycache__" not in path.parts
            )
    return tuple(sorted(selected, key=lambda path: path.relative_to(ROOT).as_posix()))


def build_bundle() -> str:
    """Render a self-indexing UTF-8 bundle with per-file SHA-256 digests."""
    sources = mathematical_sources()
    records: list[tuple[str, str, str, int]] = []
    for path in sources:
        relative = path.relative_to(ROOT).as_posix()
        content = path.read_text(encoding="utf-8").rstrip() + "\n"
        digest = hashlib.sha256(content.encode("utf-8")).hexdigest()
        records.append((relative, digest, content, content.count("\n")))

    lines = [
        "NABLAMATH MATHEMATICAL SOURCE AMALGAMATION",
        "Generated by tools/build_math_bundle.py; DO NOT EDIT BY HAND.",
        "Canonical sources remain at the paths recorded below.",
        "This artifact aggregates implemented code; it does not claim all mathematics is complete.",
        f"FORMAT_VERSION: 1",
        f"SOURCE_FILES: {len(records)}",
        f"SOURCE_LINES: {sum(record[3] for record in records)}",
        "",
        "INDEX (path | sha256 | lines)",
    ]
    lines.extend(f"{path} | {digest} | {line_count}" for path, digest, _, line_count in records)
    lines.append("")
    for path, digest, content, line_count in records:
        lines.extend(
            (
                "=" * 100,
                f"BEGIN FILE: {path}",
                f"SHA256: {digest}",
                f"LINES: {line_count}",
                "=" * 100,
                content.rstrip("\n"),
                f"END FILE: {path}",
                "",
            )
        )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail if the existing bundle is stale")
    args = parser.parse_args(argv)
    output = args.output.resolve()
    rendered = build_bundle()
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != rendered:
            print(f"Bundle matemático desatualizado: {output}")
            return 1
        print(f"Bundle matemático verificado: {output}")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    print(f"Bundle matemático criado: {output}")
    print(f"Arquivos: {len(mathematical_sources())}; linhas: {rendered.count(chr(10)) + 1}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
